name: churn-imbalance
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1


      - name: Prepare Env
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python Script.py
          

      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" > report.md
          awk 'NR%4{print "    " $0} {print ""}' metrics.txt >> report.md
          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md
          cml comment create report.md